version: "3.8"
services:
  chat_db:
    build:
      context: .
      dockerfile: ../internal/app/db/Dockerfile
    container_name: chat_db
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - chat_net
  chat_reverse_proxy:
    image: nginx
    container_name: chat_reverse_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default-local.conf:/etc/nginx/conf.d/default.conf
      - ../tools/home.domain:/etc/nginx/certs

volumes:
  db-data:


networks:
  chat_net:
    name: chat_net
