version: "3.8"
services:
  chat_db:
    build:
      context: .
      dockerfile: ../internal/app/db/Dockerfile
    container_name: chat_db
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - chat_net

volumes:
  db-data:


networks:
  chat_net:
    name: chat_net
