@baseUrl = {{url}}

# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "antoinenaza@gmail.com",
  "password": "abcdefg",
  "firstName": "Antonio",
  "lastName": "Nazario"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "antoinenaza@gmail.com",
  "password": "abcdefg"
}

###

@accessToken = {{login.response.body.accessToken}}

###

# @name logout

GET {{baseUrl}}/auth/logout
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name refresh

GET {{baseUrl}}/auth/refresh
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name getMe

GET {{baseUrl}}/users/me
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###


# @name findById

GET {{baseUrl}}/users/3
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name findUsers

GET {{baseUrl}}/users?page=1&limit=9
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name updateUser

PATCH {{baseUrl}}/users
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "firstName": "Naz",
  "lastName": "Ant"
}

###

# @name deleteUser

DELETE  {{baseUrl}}/users
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name findMyChats

GET {{baseUrl}}/chats?page=1
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name findChatMessages

GET {{baseUrl}}/chats/1/messages?limit=3&cursor=eyJJZCI6NCwiSXNQb2ludE5leHQiOmZhbHNlfQ==
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###