@baseUrl = {{url}}

# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "antoinenaza@gmail.com",
  "password": "abcdefg",
  "firstName": "Antonio",
  "lastName": "Nazario"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "antoinenaza@gmail.com",
  "password": "abcdefg"
}

###

@accessToken = {{login.response.body.accessToken}}

###

# @name getMe

GET {{baseUrl}}/users/me
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name logout

GET {{baseUrl}}/auth/logout
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}
